name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  flutter_cube: ^0.1.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  google_maps_flutter: ^2.7.0
  geolocator: ^13.0.1
  google_fonts: ^6.3.2
  flutter_native_splash: ^2.4.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_analytics: ^11.3.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/pfp/

flutter_native_splash:
  color: "#FAFCFB"
  image: assets/img/logo.png
  android: true
  ios: true 
  android_12:
    color: "#FAFCFB"
    image: assets/logo.png
    branding: assets/logo.png




