name: Nameer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  webview_flutter: ^4.4.2
  http: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  flutter_cube: ^0.1.1
  provider: ^6.1.5+1
  google_maps_flutter: ^2.7.0
  geolocator: ^13.0.1
  open_location_code: ^1.0.1
  google_fonts: ^6.3.2
  table_calendar: ^3.1.2
  flutter_native_splash: ^2.4.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_analytics: ^11.3.1
  flutter_iconpicker: ^4.0.3
  cloud_functions: ^5.0.4
  url_launcher: ^6.3.0
  firebase_messaging: ^15.1.3
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.2.2
  camera: ^0.10.5+5
  file_picker: ^8.0.3
  image_picker: ^1.1.2
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  google_place_plus: ^1.0.0  
  flutter_tts: ^3.8.5
  showcaseview: ^5.0.1
  google_mlkit_commons: ^0.11.1
  google_mlkit_text_recognition: ^0.15.1
  fl_chart: ^0.64.0 
  firebase_app_check: ^0.3.2+10
  # model_viewer_plus: ^1.9.3
  model_viewer_plus: ^1.7.0
  # flutter_gl: ^0.1.0
  # flutter_3d_obj: ^1.0.0
  # flutter_gltf: ^1.0.0
  interactive_3d: ^1.2.1
  # flutter_3d_controller: ^2.0.2
  flutter_3d_controller: ^1.4.0
  # asset_3d_viewer: ^1.0.0
  cached_network_image: ^3.3.0

dev_dependencies:
  webview_flutter: ^4.4.2
  http: ^1.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/models/ 
    - assets/pfp/
    - assets/data/
    - assets/img/onboarding1.png
    - assets/img/onboarding2.png
    - assets/img/onboarding3.png
    - assets/img/welcome.png 
    - assets/img/clothPin.png
    - assets/img/paperPin.png
    - assets/img/rvmPin.png
    - assets/img/foodPin.png
    - assets/img/nameerLeft.png
    - assets/img/nameerRight.png
    - assets/img/nameerStand.png
    - assets/img/nameerHappy.png
    - assets/img/nameerSad.png
    - assets/data/bus_stations.json
    - assets/data/metro_stations.json

flutter_native_splash:
  color: "#FAFCFB"
  image: assets/img/logo.png
  android: true
  ios: true 
  android_12:
    color: "#FAFCFB"
    image: assets/logo.png
    branding: assets/logo.png


dependency_overrides:
  intl: ^0.20.2
  syncfusion_flutter_core: ^28.1.38
  syncfusion_flutter_charts: ^28.1.38

